version: '3'

services:

  dash:
    container_name: dash
    restart: always
    volumes:
      - ./dash:/home/project/dash
      #  .\dash:/home/project/dash <-- for Windows Machines
    build: ./dash
    ports:
      - "8000:8000"
    # Workers 3 helps reolve problem with bad page loads due to thread timeouts
    command: gunicorn --workers=3 --log-level debug -b :8000 app:server

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dash
